import Head from "next/head";
import Image from "next/image";
import Advert from "../components/Advert";
import Category from "../components/Category";
import Footer from "../components/Footer";
import Hero from "../components/Hero";
import Partner from "../components/Partner";
import Testimonial from "../components/Testimonial";
import Views from "../components/views";
import styles from "../styles/Home.module.css";
import { useState, useEffect } from "react";
import { DataStore } from "@aws-amplify/datastore";
import { Course } from "../models";
import Link from "next/link";

export default function Home() {
  const [courses, setCourses] = useState([]);
  useEffect(() => {
    fetchCourse();

    async function fetchCourse() {
      const courseData = await DataStore.query(Course);
      setCourses(courseData);
      console.log(courses);
    }
    DataStore.observe(Course).subscribe((msg) => {
      fetchCourse();
      console.log("Just Updated my Course Data");
    });
  }, []);
  return (
    <div>
      <Head>
        <title>Loctech Portal</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="mb-20">
        <Hero />

        <Category />
        {courses.map((course) => (
          <Link href={`/courses/${course.id}`} key={course.id}>
            <h2>{course.name}</h2>
            <p>{course.excerpt}</p>
            <p>{course.courseDetails}</p>
            <p>{course.level}</p>
          </Link>
        ))}

        <Views />
        <Testimonial />
        <Advert />
        <Partner />
      </main>
      <Footer />
    </div>
  );
}
